# base package
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

# Copy everything from publish folder
COPY ./publish .

# final
ENTRYPOINT ["dotnet", "Training.WebAPI.dll"]
